"""Inicial

Revision ID: 26506ab51d3f
Revises: 7d9f1a9de246
Create Date: 2026-02-12 20:24:51.939947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26506ab51d3f'
down_revision = '7d9f1a9de246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forma_pago', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tiene_sena', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('monto_sena', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('monto_sena')
        batch_op.drop_column('tiene_sena')
        batch_op.drop_column('forma_pago')

    # ### end Alembic commands ###
