"""agrega campo activo a pedido

Revision ID: 387114566646
Revises: 74ee427fb0e7
Create Date: 2026-02-15 19:02:21.193581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387114566646'
down_revision = '74ee427fb0e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
