"""quitar_fecha_estimada_y_agregar_fechas_estado

Revision ID: 39eeed38aac9
Revises: 8352b31cdd65
Create Date: 2026-02-16 12:20:00.293632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39eeed38aac9'
down_revision = '8352b31cdd65'
branch_labels = None
depends_on = None


def upgrade():
    # 1) Agregar pendiente_at (solo esta nueva)
    # recreate="always" evita el bug de dependencias circulares en SQLite batch mode
    with op.batch_alter_table("pedido", schema=None, recreate="always") as batch_op:
        batch_op.add_column(sa.Column(
            "pendiente_at",
            sa.DateTime(),
            nullable=True,
            server_default=sa.text("CURRENT_TIMESTAMP")
        ))

    # 2) Backfill: conservar la fecha real usando created_at
    op.execute("UPDATE pedido SET pendiente_at = created_at WHERE pendiente_at IS NULL")

    # 3) Borrar fecha_estimada (en otro batch separado, también recreate always)
    with op.batch_alter_table("pedido", schema=None, recreate="always") as batch_op:
        batch_op.drop_column("fecha_estimada")

    # 4) (Opcional) poner NOT NULL. Si vuelve a dar guerra, borrá este bloque.
    with op.batch_alter_table("pedido", schema=None, recreate="always") as batch_op:
        batch_op.alter_column("pendiente_at", nullable=False, server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('fecha_estimada', sa.DATE(), nullable=True))
        batch_op.drop_column('pendiente_at')

    # ### end Alembic commands ###
