"""agrega fecha_estimada

Revision ID: 74ee427fb0e7
Revises: 26506ab51d3f
Create Date: 2026-02-15 18:17:14.475734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ee427fb0e7'
down_revision = '26506ab51d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_estimada', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('fecha_estimada')

    # ### end Alembic commands ###
