"""Fechas Pedidos

Revision ID: 8352b31cdd65
Revises: 98346b72b5c2
Create Date: 2026-02-16 11:52:23.464885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8352b31cdd65'
down_revision = '98346b72b5c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('en_curso_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('finalizado_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('finalizado_at')
        batch_op.drop_column('en_curso_at')

    # ### end Alembic commands ###
