"""Add pendiente_at back

Revision ID: 9765e9493c9c
Revises: e4c9290610c8
Create Date: 2026-02-21 19:34:13.225788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9765e9493c9c'
down_revision = 'e4c9290610c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pendiente_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('pendiente_at')

    # ### end Alembic commands ###
