"""agrega campo activo nulleable y default

Revision ID: 98346b72b5c2
Revises: 387114566646
Create Date: 2026-02-15 19:05:56.264523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98346b72b5c2'
down_revision = '387114566646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.alter_column('activo',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.alter_column('activo',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
