"""Pagos + refactor pedido

Revision ID: e4c9290610c8
Revises: 39eeed38aac9
Create Date: 2026-02-21 19:00:55.980931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c9290610c8'
down_revision = '39eeed38aac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pago_comprobante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_bytes', sa.Integer(), nullable=True))

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forma_pago_preferida', sa.String(length=50), nullable=True))
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.execute("UPDATE pedido SET forma_pago_preferida = forma_pago")

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('forma_pago')
        batch_op.drop_column('tiene_sena')
        batch_op.drop_column('pendiente_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pendiente_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('tiene_sena', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('forma_pago', sa.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        op.execute("UPDATE pedido SET forma_pago = forma_pago_preferida")
        batch_op.drop_column('forma_pago_preferida')

    with op.batch_alter_table('pago_comprobante', schema=None) as batch_op:
        batch_op.drop_column('size_bytes')

    # ### end Alembic commands ###
